[package]
name = "boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
com_logger = "0.1.1"
log = "0.4.20"
uefi = { version = "0.24.0", features = ["alloc"] }
uefi-services = "0.21.0"
windows-sys = { version = "0.48.0", features = [
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
] }
